### ISSUE TITLE
[BUG]Failed to insert data with a union type

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb-ui#104]
Say we have schema as following.

module default {
    abstract type Place {
        property name -> str;
        property abbr -> str;
    }

    type Country extending Place {
    }

    type State extending Place {
        required link country -> Country;
    }

    type City extending Place {
        required link state -> State;
    }

    type District extending Place {
        required link city -> City;
    }

    type Street extending Place {
        required link districtOrCity -> District|City; # Assumed there are some Street belong to City instead of District.
    }
}
And we fill some data via edgedb ui.
when some Street link to City directly, it will fail.

![image](https://user-images.githubusercontent.com/16233397/208296810-c42a5d9d-c4e9-4c7b-abd8-792695ee6a00.png)

edgedb version is 3.9

**Comment by raddevon** [comment]
In your `districtOrCity` `select` query, are you trying to select an object of one of two types — `City` or `default` — with an `id` property matching the one you're filtering for? Just want to make sure I understand what you're trying to do.

If so, you won't be able to do it by using [the union operator (`|`)](https://www.edgedb.com/docs/stdlib/type#operator::typeor) to specify the types like you've done here. Here's an example of how you'd do it with a schema like this:

```
module default {
  abstract type Person {
    required property name -> str;
  }
  type Developer extending Person;
  type Attorney extending Person;
  type Marketer extending Person;
}
```

If you had this schema and wanted to select just from `Developer`s or `Attorney`s, you'd do it like this:

```
select {Developer, Attorney} filter name = 'Pat';
```

Does that help?

**Comment by raddevon** [comment]
@jaclarke Ah, OK. Thanks for clarifying that.
