### ISSUE TITLE
Repl | Update the ASCII art font and the margin to welcome text according to Figma mockup

### ISSUE THREAD

**Issue by shougan** [edgedb/edgedb-ui#113]
[Figma](https://www.figma.com/file/430gInXr2xbFqBOLTCmpHJ/Cloud_UI?node-id=357%3A7018&t=qRUnjsvXMJddXu9Z-0)

<img width="595" alt="image" src="https://user-images.githubusercontent.com/1627031/213939244-2b9798cd-b7d3-4aec-b7e9-d2778bae6943.png">

**Comment by DijanaPavlovic** [comment]
This is fixed, so I'll close the issue now.
