### ISSUE TITLE
Repl | Update the repl cursor colors

### ISSUE THREAD

**Issue by shougan** [edgedb/edgedb-ui#114]
[Figma](https://www.figma.com/file/430gInXr2xbFqBOLTCmpHJ/Cloud_UI?node-id=357%3A7018&t=qRUnjsvXMJddXu9Z-0)

Update the repl cursor light theme color to `#808080 `and dark theme to `#595959`

<img width="926" alt="image" src="https://user-images.githubusercontent.com/1627031/213939366-3bd02969-29a0-4a08-b92b-7f5a98486d36.png">

**Comment by DijanaPavlovic** [comment]
This is fixed. I'll close the issue.
