### ISSUE TITLE
Welcome screen | Update buttons corner radius to 4px

### ISSUE THREAD

**Issue by shougan** [edgedb/edgedb-ui#119]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/1627031/213939807-e10e9d8c-532e-4914-931a-35c65f12164d.png">

**Comment by DijanaPavlovic** [comment]
Hey @shougan can you check the current version? I pushed yesterday this fix when I added 4th button. If everything is okay I think we can close this one.
