### ISSUE TITLE
Show `EdgeDB Cloud` logo if there's `edgedb.cloud` in the UI URL

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-ui#160]
Our "local" UI isn't going to be fully local in the immediate future as it will be possible to access cloud instances with it. We should display an "EdgeDB Cloud" logo if the UI is served from the `edgedb.cloud` domain.

<img width="707" alt="CleanShot 2023-03-06 at 11 19 36@2x" src="https://user-images.githubusercontent.com/239003/223281832-c1709dfb-bda7-445c-89e8-8c9e0e3612a3.png">

cc @jaclarke @DijanaPavlovic @shougan

**Comment by 1st1** [comment]
@DijanaPavlovic Dijana, this is relatively high priority so please take a look before Wednesday. Roman should be able to give you a "cloud" version of the logo for the UI.

**Comment by shougan** [comment]
The "LOCAL" and "CLOUD"  are not the images, it's the font, and currently it's wrong size/weight

<img width="672" alt="image" src="https://user-images.githubusercontent.com/1627031/223282725-bc48de83-888f-471f-9098-9082731ffbcd.png">

**Comment by shougan** [comment]
Done
[Figma](https://www.figma.com/file/430gInXr2xbFqBOLTCmpHJ/Cloud_UI?node-id=357%3A7018&t=E8kfwE2ZOrHDVd3a-0)

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/1627031/223287123-32b0639f-044e-4440-8277-2980b04f2994.png">
