### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by kubeworkz** [edgedb/edgedb-ui#169]
Is it possible to activate the login screen? Cheers, Dave

**Comment by raddevon** [comment]
It's already active, but we bypass it by default for you. If you navigate to http://localhost:<instance-port>/ui/_login, you can get to it. You could also run `edgedb ui --print-url` and just copy the portion of the URL up to the `?`.

Closing now, but feel free to re-open if that doesn't fully address your question.
