### ISSUE TITLE
"Apply Filter" in Data Explorer blocks on initial query 

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb-ui#220]
While data is loading, the "Apply Filter" button is enabled but doesn't appear to take effect until after the existing request returns. This is very slow when the initial load of an object takes a long time (30-60+ seconds for one of our object types, though I think this is because we have a lot of links) and you want to drill down to a small number of objects or single object but can't until that unneeded first load finishes. 

Less important corollary is that there's no visual indication that the filter is taking effect, such as the button being disabled until you dirty the filter field, etc

Looking at the network requests, it looks like the request for the filtered version blocks on kicking off until the first request returns. Ideally doing a filter would cancel the current request and start the new one.

**Comment by jaclarke** [comment]
Fixed in https://github.com/edgedb/edgedb-ui/pull/225
