### ISSUE TITLE
The error with `float32` rendering appeared

### ISSUE THREAD

**Issue by iaroslaff** [edgedb/edgedb-ui#235]
The error showed itself again
[https://github.com/edgedb/edgedb-ui/pull/214](url)

![Screenshot (7)](https://github.com/edgedb/edgedb-ui/assets/7544341/8479f18a-7ccd-4d0b-baad-449c61db3f0a)
![Screenshot (8)](https://github.com/edgedb/edgedb-ui/assets/7544341/8487017a-03b5-43a7-a8ae-56cd4855bb44)

**Comment by iaroslaff** [comment]
I'm using EdgeDB Cloud, version 3.2

**Comment by jaclarke** [comment]
Ok, should be fixed now. The latest ui updates hadn't been deployed to the cloud.

**Comment by iaroslaff** [comment]
Сan be closed, I checked, the fixes are already applied :ok_hand:
