### ISSUE TITLE
Feature request - add properties of link in table.

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb-ui#252]
Say I have a schema as following:

type Bom{
   title: str;
   components: Component {relationship:str;};
   ...
}

type Component {
   some properties ...
}

But I don't find @relationship anywhere, neither Bom UI nor Component UI. I think these properties should be show in the table of Component as `@relationship`;

![image](https://github.com/edgedb/edgedb-ui/assets/16233397/d946f4f5-50a4-4a1e-bafe-9a2778b0b183)
![image](https://github.com/edgedb/edgedb-ui/assets/16233397/60dbbc56-fd61-42b1-9fb0-e1d9457133b8)

**Comment by jackfischer** [comment]
Duplicates #11
