### ISSUE TITLE
`Invalid parameter cast` for array of tuples

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb-ui#253]
```
type Example {
    required x: str;
    required y: str;
}
```

```
with  examples := <array<tuple<
    x: str,
    y: str,
  >>>$examples,

for e in array_unpack(examples) union (
  insert Example {
    x:=e.x,
    y:=e.y
  }
)
```

<img width="598" alt="Screenshot 2023-09-14 at 4 03 02 PM" src="https://github.com/edgedb/edgedb-ui/assets/6811459/4b54d74b-1f06-467e-a0a8-1cedef3accd7">

**Comment by raddevon** [comment]
In the CLI REPL, I get `Unimplemented input type descriptor: Array(ArrayTypeDescriptor { id: 72fb1422-dca3-5923-b314-f19f416e38c7, type_pos: TypePos(1), dimensions: [None] })`

**Comment by jackfischer** [comment]
Thank you @jaclarke - should i file separately for the CLI?

**Comment by quinchs** [comment]
> Do you know what the priority is for these issues

No, I don't, but I can work on that now.

> how to actually represent the input/how it would work with rustyline?

I think we could just repeatedly ask for the inner element input until the array is completed via keybind? I'll play around and find something.
