### ISSUE TITLE
Zero UUID isn't valid as a query param

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb-ui#373]
EdgeDB 4.8

Working:
<img width="1833" alt="Screenshot 2024-11-05 at 1 52 30 PM" src="https://github.com/user-attachments/assets/1c6fcc75-bedf-4bbd-a045-f36f4b46b265">

Not working: error is "invalid uuid"
<img width="916" alt="Screenshot 2024-11-05 at 1 52 44 PM" src="https://github.com/user-attachments/assets/f200e023-62c3-47ef-ba12-bb34e9134040">

**Comment by scotttrinh** [comment]
Couldn't repro on local 4.8 UI instance. Can you triple check the zero UUID? 

![696dc222e33f782342c4d0feb3115a6d](https://github.com/user-attachments/assets/594e2416-f1e6-4088-9504-ce01aeccbcc4)

**Comment by scotttrinh** [comment]
That's a good question, and I have a technical answer, but it's unsatisfying: The UI does some client-side checking which requires the dashes to be in the typical places. The server is happy to "Do What I Mean" when converting the string:

```
select <uuid>"00000000-00000000-00000000-00000000";
{00000000-0000-0000-0000-000000000000}

select <uuid>"00000000000000000000000000000000";
{00000000-0000-0000-0000-000000000000}
```

**Comment by jackfischer** [comment]
Cool, above my paygrade at that point, thank you very much for looking.
