### ISSUE TITLE
REPL should warn wether access policies have been applied to the request to help understand

### ISSUE THREAD

**Issue by dotlouis** [edgedb/edgedb-ui#49]
[x-post from discord](https://discord.com/channels/841451783728529451/1012717851792125952)
I divided the post into two different issues for clarity. The first one the post reference is #48 

Hi all,

I fiddled around with my project trying to set up access policies and it took me a while to understand why I did not see my data in the REPL queries before seeing the little green checkbox: "Disable Access Policies".

I don't know how hard it is to detect the use of access policies, but it would be very helpful for beginners to have an indication that their query was restricted and that they can disable access policies for debugging and prototyping purposes.

I would suggest adding a little "heads-up" on queries that return limited results dues to policies.
I made a little prototype to illustrate:

![CleanShot 2022-08-26 at 15 40 53@2x](https://user-images.githubusercontent.com/1891109/186932400-2ab12f55-5e38-4308-b438-81e33e54afe6.png)

**Comment by 1st1** [comment]
@jaclarke I think this is also a good idea.

**Comment by jaclarke** [comment]
I've added a note to the repl result to indicate when the query was run with access policies disabled in this PR: #62.

The second part is slightly more difficult. I think to properly implement that we need the LSP feature to be able to analyse queries, and check which object types are involved in the query, so we can see if there are any access policies that could affect the result. Currently, we could do a more limited check of the object types in the result codec, but that would miss cases where the object type does not appear directly in the result. I'm not sure if that could end up being misleading if users take the lack of an access policy message to mean that there are no access policies affecting the query.

**Comment by dotlouis** [comment]
Very cool. I think knowing that access policies are disabled is already a great improvement to help us understand what is going on. Thanks
