### ISSUE TITLE
UI queries failing due to unescaped keywords in schema

### ISSUE THREAD

**Issue by danecando** [edgedb/edgedb-ui#53]
I have a type in my schema called Group which I escape as `Group` or `group`. This is causing failures in the UI because the queries are being sent without group being escaped. I understand that I am to blame and will not be offended if this never gets fixed unless I do it myself

![Screen Shot 2022-08-31 at 9 11 18 PM](https://user-images.githubusercontent.com/3721977/187811517-a4d2bb13-8275-47b0-b8ee-b218334f7726.png)
![Screen Shot 2022-08-31 at 9 11 43 PM](https://user-images.githubusercontent.com/3721977/187811519-da348a57-82c5-4455-a0d4-e415425746a0.png)

**Comment by jaclarke** [comment]
Good catch, the ui should be escaping these names. I've added a fix for this, which will be released in EdgeDB 2.2 sometime this week.
