### ISSUE TITLE
SSH Certification problem while deploying edgedb to GCP 

### ISSUE THREAD

**Issue by chun92** [edgedb/edgedb-ui#67]
### What Happened
* I'm newbie of kubernetes, so I just followed the [manual](https://www.edgedb.com/docs/guides/deployment/gcp).
I succeeded in setting the edgedb instance and linking the remote instance, and add following code to deployment.yaml to be enable the edgedb ui.

`- name: EDGEDB_SERVER_ADMIN_UI value: enabled`

After that, I notice that edgedb ui is not working because of ssl certification error.
I think that I need to apply some certification for kubernetes, but I don't know how to do it.

Could you give me some guide for it or update the [manual](https://www.edgedb.com/docs/guides/deployment/gcp)?
I think that your kind explanation would be great helpful to a beginner like me!

<img width="732" alt="image" src="https://user-images.githubusercontent.com/3786258/190448449-c4ebe9c5-8c9a-4a38-a485-e866ad58f1b1.png">

**Comment by elprans** [comment]
EdgeDB uses a self-signed TLS certificate which is not trusted by your browser.  There are two options: 

1) Ignore the error ("Advanced" ...)
2) Provide a properly signed TLS certificate for the host on which EdgeDB is exposed and then configure the server to use it via `EDGEDB_SERVER_TLS_CERT` and `EDGEDB_SERVER_TLS_KEY`

**Comment by chun92** [comment]
Thank you @elprans.
I change the TLS certificate with a properly signed one.
It works well.
