### ISSUE TITLE
[Bug] Self-Referencing links are getting deleted after saving

### ISSUE THREAD

**Issue by madebyfabian** [edgedb/edgedb-ui#80]
Hey there,
first of all, I am super impressed on the work of EdgeDB, the CLI and the UI. Looks very promising!

I am completely new, so maybe I made a mistake with the schema.

## Reproduction

I have this schema:

```
type User {
    property name -> str;
    multi link followingUsers -> User;
}
```

And this is already migrated without any issues. I now want to assign multiple `User` objects to the `followingUsers` multi link via the UI. I can assign them, when I now `Review Changes` it looks like this:

![Bildschirm­foto 2022-11-24 um 19 16 23](https://user-images.githubusercontent.com/32813692/203846689-db7b9922-0917-46e7-8602-b896175bcae4.jpg)

and the UI is also displaying that there are 3 related `User` entries in this `followingUsers` field.

**But when I now commit those changes**, it seems that the UI/the DB removes all links except for when I link the object to itsself. (In my example, when I have a `User` and I link it to the exact same `User`, this works. But I think it should actually be the other way round, so that objects cannot self-reference but can reference to other objects.

**Comment by elprans** [comment]
@jaclarke, this is a scoping bug, we need to make sure nested object refs are `detached` (or aliased in top `with`).
