### ISSUE TITLE
Horizontal scroll bar is not shown when columns beyonded the width of table.

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb-ui#92]
Hello, I can't find the Horizontal scroll bar in the button of window when the width of columns beyond the border of table.
So pls consider this a feature or bug? thanks.

![Untitled-2](https://user-images.githubusercontent.com/16233397/205867384-e49b5d76-bfd0-4c2a-927f-05e44150791d.jpg)

**Comment by raddevon** [comment]
I can't reproduce this on my side. I can't *see* the scrollbar because my OS auto-hides it, but I'm able to scroll.

Maybe this is what you're experiencing as well? Maybe the element is scrollable, but the scrollbar is being hidden by your OS? What OS are you running?

**Comment by AnsonHwang86** [comment]
Hello, thanks. Yes, It is being hidden by Chrome.
I use `shift + scroll` to scroll.
Can this scroll bar be appeared alway?
My OS is `windows 11`
`Chrome Version 108.0.5359.73 (Official Build) (64-bit)`
edgedb V2.7

**Comment by raddevon** [comment]
On my system, the browser respects the OS-level setting for this, so, assuming that's also the case with Chrome/Windows 10, let's try changing that. In Windows 10, it should be in Settings > Accessibility > Visual Effects. Turn "Always show scrollbars" to "On." Does that make your scrollbars always visible in the data view?

**Comment by AnsonHwang86** [comment]
Thanks
