### ISSUE TITLE
Rendering problem when attempting to edit empty set

### ISSUE THREAD

**Issue by samandarco** [edgedb/edgedb-ui#98]
You can reproduce the issue by attempting to edit any empty string/set, in the following case I tried to edit empty field `modern_name`.

![telegram-cloud-photo-size-2-5233573669614241837-y](https://user-images.githubusercontent.com/2642041/206851099-196a51e9-af06-4c50-936a-5c636c37ba22.jpg)

Then got following issue:
![telegram-cloud-photo-size-2-5233573669614241835-y](https://user-images.githubusercontent.com/2642041/206851186-00211ee5-14f3-4e5d-8246-4ffcc2962896.jpg)

**Comment by jaclarke** [comment]
Looks like this was fixed by #96
